#!/usr/bin/perl
&notify("Penguin Applet Running!"); # note: supplied by server
foreach $i (1..10) {
    print("$i bottle of beer(s) on the wall...\n");
}
$j = reverse "!nur yllufsseccus sah margorp niugnep rehtona tsuj";
print $j, "\n";
return $j;
